# Generated by Django 4.2.3 on 2023-08-03 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_is_email_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrammarquestion',
            name='grammar_question',
        ),
        migrations.RemoveField(
            model_name='usergrammarquestion',
            name='user',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='user_answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GrammarQuestion',
        ),
        migrations.DeleteModel(
            name='UserGrammarQuestion',
        ),
    ]
