# Generated by Django 3.2.11 on 2023-10-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrammarContent',
            new_name='WritingContent',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='grammar_content',
            new_name='writing_content',
        ),
        migrations.AlterModelTable(
            name='writingcontent',
            table='api_writing_content',
        ),
    ]
