# Generated by Django 3.2.11 on 2023-10-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231012_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_location', models.CharField(max_length=255)),
                ('file_management_code', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
            ],
        ),
    ]
