# Generated by Django 3.2.11 on 2023-10-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='ContentData',
        ),
    ]
