# Generated by Django 4.2.4 on 2023-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_difficulty_remove_question_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text_ko',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.JSONField(null=True),
        ),
    ]
