# Generated by Django 3.2.11 on 2023-11-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_content_contentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
