# Generated by Django 4.2.4 on 2023-09-16 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_question_question_text_ko_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='GrammarContent',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='grammar_content',
        ),
    ]
