# Generated by Django 3.2.11 on 2023-11-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_max_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='corrected_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
