# Generated by Django 4.2.4 on 2023-09-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_question_grammarcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarcontent',
            name='question_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterModelTable(
            name='grammarcontent',
            table='api_grammar_content',
        ),
        migrations.DeleteModel(
            name='ConnectedAccount',
        ),
    ]
