# Generated by Django 3.2.11 on 2023-11-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_note_corrected_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquestion',
            name='use_yn',
            field=models.BooleanField(default=True),
        ),
    ]
