# Generated by Django 4.2.4 on 2023-09-22 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_banner_coupon_expiry_date_grammarcontent_sequence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammarcontent',
            old_name='question_text',
            new_name='content_text',
        ),
        migrations.RenameField(
            model_name='grammarcontent',
            old_name='question_text_en',
            new_name='content_text_en',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_detail', models.TextField(blank=True, null=True)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('content_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grammarcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grammarcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
