# Generated by Django 4.2.4 on 2023-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_question_text_grammarcontent_content_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcontent',
            name='content_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('contens', '문제이상'), ('answer', '답변이상')], max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(choices=[(1, '대분류'), (2, '중분류'), (3, '소분류')], default=1),
        ),
    ]
