# Generated by Django 3.2.11 on 2023-10-06 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_grammarcontent_content_code_report_report_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_email_registered',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['nickname'], name='api_profile_nicknam_a2d5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['last_login_at'], name='api_profile_last_lo_ffe60e_idx'),
        ),
    ]
